### ISSUE TITLE
Missing Public Key for Trusty on Travis

### ISSUE THREAD

**Issue by labboy0276** [lando/hyperdrive#10]
**Describe the bug**
When I install and run hyperdrive on travis, it gives me a NO_PUBKEY for https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease

**To Reproduce**
Setup travis to install and run hyperdrive like this:
```yml
before_install:

  # Install Hyperdrive
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - sudo bash -c "curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.5.4/hyperdrive > /usr/local/bin/hyperdrive"
  - sudo chmod +x /usr/local/bin/hyperdrive

script:
  # Setup hyperdrive
  - hyperdrive -y --name "James T. Kirk" --email kirk@enterprise.mil
```

**Error**
```bash
Err:26 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
Hit:27 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:28 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Hit:29 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Reading package lists... Done
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
FAILED WITH CODE 100!
```

**Expected behavior**
It installs hyperdrive as expected.

**Additional context**
I was able to fix this by adding this to my travis file:
```yml
  # Add Repo key to prevent hyperdrive install errors.
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
```
